### PR TITLE
Add AI nice to haves

### PR DESCRIPTION
**Pull request by Bobowoo2468**
Added nice to haves with OpenAI integration

### CODE REVIEW

**Comment by Bobowoo2468** [comment]
Deconflict all merge conflicts, will add back details incrementally.

**Review by YipWayne — DISMISSED** [review]
LGTM

**Review by yzhedwin — CHANGES_REQUESTED** [review]
## BUG 1 background scrolled down when modal shows up: 
image

## BUG 2 Original code not updated on left panel
### Original code
image
### Translate modal
image

## BUG 3 Translate does not translate current code
image

**Review by yzhedwin — APPROVED** [review]
LGTM

**Pull request merged**
